In [1]:
import tensorflow as tf
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [2]:
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [3]:
#numpy arrays into tensor
import numpy as np
numpy_A=np.arange(1,25,dtype=np.int32)#create array 1 to 25
#usuallly capitals used for matrix or temsor and small letters for vectors in tensorflow
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [4]:
A=tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [5]:
A=tf.constant(numpy_A,shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [6]:
A=tf.constant(numpy_A,shape=(3,8))
A

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

getting information from tensors


shape
rank
axis or dimension
size

In [7]:
# rank4 tensor
rank_4_tensor=tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [8]:
rank_4_tensor.shape,
rank_4_tensor.ndim,
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [9]:
print("datatype of every element",rank_4_tensor.dtype)
print("no. of dimensions (rank)",rank_4_tensor.ndim)
print("shape of tensor",rank_4_tensor.shape)
print("elements along 0 axis",rank_4_tensor.shape[0])
print("elements along last axis",rank_4_tensor.shape[-1])
print("total no. of elements",tf.size(rank_4_tensor))
print("total no. of elements",tf.size(rank_4_tensor).numpy)

datatype of every element <dtype: 'float32'>
no. of dimensions (rank) 4
shape of tensor (2, 3, 4, 5)
elements along 0 axis 2
elements along last axis 5
total no. of elements tf.Tensor(120, shape=(), dtype=int32)
total no. of elements <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int32, numpy=120>>


#indexing

tensors can be indexed just like python lists


In [10]:
#get the frst 2 elements of each dimension of our tensor

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [11]:
some_list=[1,2,3,4]
some_list[:2]

[1, 2]

In [12]:
rank_4_tensor.shape


TensorShape([2, 3, 4, 5])

In [13]:
#get 1st element from each dimenssion from each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [14]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [15]:
#create rank2 ie,dimension-2
import tensorflow as tf

rank_2_tensor = tf.constant([[10,7],
                           [3,4]])
rank_2_tensor.shape,rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [16]:
#get the last ite of each row

rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [17]:
#add extra dimension

rank_3_tensor = rank_2_tensor[...,tf.newaxis] #...=on all previous axis before last one
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [18]:
#or
rank_3_tensor = rank_2_tensor[:,:,tf.newaxis]
rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [19]:
#alternative to tf.newaxis

tf.expand_dims(rank_2_tensor,axis=-1)#-1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [20]:
tf.expand_dims(rank_2_tensor,axis=1)#expand 0 axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [21]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

###manipulating tensors
(tensor operations) like + - * /

element wise

In [22]:
tensor = tf.constant([[10,7],[3,4]])
#addition
tensor+10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [23]:
#subtraction
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [24]:
#multiplication
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [25]:
#original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [26]:
#changed
tensor=tensor+10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [27]:
#using built-in functions
tf.multiply(tensor,10) #changed tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]], dtype=int32)>

###matrix multiplication
one of the most common

In [28]:
tensor*tensor
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [29]:
#using tensor flow

tf.matmul(tensor,tensor)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [30]:
#with python operator "@"
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [31]:
x=tf.constant([[1,2],
               [3,4],
               [5,6]])

y=tf.constant([[7,8],
               [9,10],
               [11,12]])


x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [33]:
#matrix multiply of same shape
tf.matmul(x,y)

InvalidArgumentError: ignored

In [ ]:
#rules inner dimensions muust match
# result will have dimensions equal to outer dimensions

In [34]:
#reshape
tf.reshape(y,shape=(2,3))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [35]:
#try to multiply now
x@tf.reshape(y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [36]:
tf.matmul(tf.reshape(x,shape=(2,3)),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [37]:
#you can also use transpose
x,tf.transpose(x),tf.reshape(x,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [38]:
tf.matmul(tf.transpose(x),y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

you can do tensor matrix multtiplication by
tf.matmul()

or
tf.tensordot()

or
@ operator

when matrix multipliation generally transpose rather than reshape to fulfill the conditions for matrix multiplication


###changing the datatype of the tensor
you can change the datatype ie. from 32  bit to 1 bit coz it runs faster in certain gpus and tpus


In [39]:
#creating tensor with default datatype(float32)

a=tf.constant( [1.7,1.4])
a.dtype

tf.float32

In [40]:
b=tf.constant( [10,7])
b.dtype

tf.int32

In [41]:
#changing from float 32 to float 16(reduced precision)
c=tf.cast(a,tf.float16)


In [42]:
c.dtype

tf.float16

In [43]:
#changing int 32 to float 32
d=tf.cast(b,tf.float32)

In [44]:
d.dtype

tf.float32

In [45]:
d

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  7.], dtype=float32)>

### TENSOR AGGREGATION
defn: condensing them from multiple values to a smaller amount of values

max min mean  sum etc

In [46]:
#create a random tensor
import numpy as np

a= tf.constant(np.random.randint(0,100,size=50))
a

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([98,  2, 72, 61, 68, 78, 86, 60, 55, 53, 90, 64, 34, 32, 19, 65, 41,
       52, 85, 31, 67,  5, 46, 13, 43, 32, 39, 92, 37, 59, 60, 79, 98, 38,
       36, 51, 86, 59, 42, 56, 68,  5, 67, 58, 76, 23, 37, 47,  2, 53])>

In [47]:
tf.size(a),a.ndim,a.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, 1, TensorShape([50]))

In [48]:
#find the minimum
tf.reduce_min(a)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [49]:
#find the maximum
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [50]:
#find the mean
tf.reduce_mean(a)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [51]:
#find the sum
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=int64, numpy=2620>

In [52]:
import math
mean=tf.reduce_mean(a)
meanred=a-mean
meansq=meanred*meanred
sum=tf.reduce_sum(meansq)
variance=sum/50
standdev=math.sqrt(variance)

mean,meanred,meansq,sum,variance,standdev




(<tf.Tensor: shape=(), dtype=int64, numpy=52>,
 <tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([ 46, -50,  20,   9,  16,  26,  34,   8,   3,   1,  38,  12, -18,
        -20, -33,  13, -11,   0,  33, -21,  15, -47,  -6, -39,  -9, -20,
        -13,  40, -15,   7,   8,  27,  46, -14, -16,  -1,  34,   7, -10,
          4,  16, -47,  15,   6,  24, -29, -15,  -5, -50,   1])>,
 <tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([2116, 2500,  400,   81,  256,  676, 1156,   64,    9,    1, 1444,
         144,  324,  400, 1089,  169,  121,    0, 1089,  441,  225, 2209,
          36, 1521,   81,  400,  169, 1600,  225,   49,   64,  729, 2116,
         196,  256,    1, 1156,   49,  100,   16,  256, 2209,  225,   36,
         576,  841,  225,   25, 2500,    1])>,
 <tf.Tensor: shape=(), dtype=int64, numpy=30572>,
 <tf.Tensor: shape=(), dtype=float64, numpy=611.44>,
 24.727312834192073)

In [53]:
#OR
#variance=

import tensorflow_probability as tfp
tfp.stats.variance(a)

<tf.Tensor: shape=(), dtype=int64, numpy=611>

In [54]:
#standard deviation =

tf.math.reduce_std(tf.cast(a,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=24.724077>

###find positional maximun and mimimum

In [56]:
tf.random.set_seed(42)
f=tf.random.uniform(shape=[50])
f


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [57]:
#find positional max ie argmax
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [58]:
#index
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [59]:
#posnal minimum
tf.argmin(f)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [60]:
f[16]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

###squeezing a tensor
removing single dimension

In [65]:
tf.random.set_seed(42)
g=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [66]:
g.shape


TensorShape([1, 1, 1, 50])

In [68]:
g_squeezed=tf.squeeze(g)
g_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

###one hot encoding tensor


In [69]:
#create a list for indices
some_list=[0,1,2,3]
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [70]:
tf.one_hot(some_list,depth=4,on_value="yes",off_value="no")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yes', b'no', b'no', b'no'],
       [b'no', b'yes', b'no', b'no'],
       [b'no', b'no', b'yes', b'no'],
       [b'no', b'no', b'no', b'yes']], dtype=object)>

### squaring log squareroot

In [72]:
h=tf.range(1,10)
h

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [73]:
#squareit
tf.square(h)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [77]:
#squareroot method requires non int type data
tf.sqrt(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [80]:
#find log
tf.math.log(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

###finding access to gpus


In [84]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [1]:
import tensorflow as tf
tf.config.list_physical_devices("GPU")


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
!nvidia-smi


Wed Jul 26 20:17:27 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------