In [6]:
from google.colab import drive

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt



In [9]:
df =pd.read_csv('/content/drive/MyDrive/machine learning udemy r/Machine Learning A-Z (Codes and Datasets)/Part 2 - Regression/Section 8 - Decision Tree Regression/Python/Position_Salaries.csv')

In [10]:
df

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [11]:
X = df.iloc[:,1:-1].values
Y = df.iloc[:,-1].values

In [12]:
X

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [13]:
Y


array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
        300000,  500000, 1000000])

In [14]:
from sklearn.tree import DecisionTreeRegressor


In [15]:
regressor = DecisionTreeRegressor(random_state=0)

In [16]:
regressor.fit(X,Y)

DecisionTreeRegressor(random_state=0)

In [18]:
regressor.predict([[6.5]])


array([150000.])

In [ ]:
X_grid = np.arange(min(X), max(X), 0.01)
X_grid


In [ ]:
X_grid = X_grid.reshape((-1, 1))
X_grid

In [ ]:
plt.scatter(X, Y, color = 'red')
plt.plot(X_grid, regressor.predict(X_grid), color = 'blue')
plt.title('Truth or Bluff (Decision Tree Regression)')
plt.xlabel('Position level')
plt.ylabel('Salary')
plt.show()

In [21]:
var = input("enter the level : ")
regressor.predict([[var]])


enter the level : 7.7


array([300000.])