In [1]:
from google.colab import drive
drive.mount('/content/drive')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Mounted at /content/drive


In [2]:
dataset = pd.read_csv('/content/drive/MyDrive/machine learning dataset/personal/ml model 1.csv')

In [3]:
dataset

Timestamp  age(eg . 18-22) favourite subject among the following  \
0  11/28/2023 0:32:40               19                                 maths   
1  11/28/2023 0:32:53               21                                 maths   
2  11/28/2023 0:33:10               20                                sports   
3  11/28/2023 0:33:16               20                                sports   
4  11/28/2023 0:34:10               19                                 maths   

  favourite food   cgpa in first year(be honest) eg.2.5  
0    litti chokha                                   7.0  
1           lassi                                   8.0  
2        biriyani                                   7.2  
3           lassi                                   6.5  
4        biriyani                                   7.6

In [4]:
X = dataset.iloc[:,1:-1].values
Y = dataset.iloc[:,-1].values

In [5]:
X


array([[19, 'maths', 'litti chokha'],
       [21, 'maths', 'lassi'],
       [20, 'sports', 'biriyani'],
       [20, 'sports', 'lassi'],
       [19, 'maths', 'biriyani']], dtype=object)

In [7]:
Y

array([7. , 8. , 7.2, 6.5, 7.6])

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

columns_to_encode = [1,2]

# Create a ColumnTransformer object
ct = ColumnTransformer(transformers=[
    ('encoder1', OneHotEncoder(), columns_to_encode[0:1]),
    ('encoder2', OneHotEncoder(), columns_to_encode[1:2]),
], remainder='passthrough')

# Transform the data
X = ct.fit_transform(X)

In [14]:
X

array([[1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 19, 'maths'],
       [1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 21, 'maths'],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 20, 'sports'],
       [1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 20, 'sports'],
       [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 19, 'maths']], dtype=object)

In [12]:
X

array([[1.0, 0.0, 1.0, 0.0, 1.0, 19, 'maths'],
       [1.0, 0.0, 0.0, 1.0, 0.0, 21, 'maths'],
       [0.0, 1.0, 1.0, 0.0, 0.0, 20, 'sports'],
       [1.0, 0.0, 0.0, 1.0, 0.0, 20, 'sports'],
       [0.0, 1.0, 1.0, 0.0, 0.0, 19, 'maths']], dtype=object)